name: Deploy WSO2 API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract apictl
        run: |
          curl -L -o apictl.tar.gz https://github.com/wso2/product-apim-tooling/releases/download/v4.7.2/apictl-4.7.2-linux-amd64.tar.gz
          tar -xzf apictl.tar.gz
          ls -la
          ls -la apictl

      - name: Add apictl to PATH
        run: |
          echo "$GITHUB_WORKSPACE/apictl" >> $GITHUB_PATH

      - name: Check apictl version
        run: |
          apictl version

      - name: Configure WSO2 environment
        run: |
          apictl add env dev \
            --apim "${{ secrets.WSO2_APIM_URL }}"

      - name: Login to WSO2 API Manager
        run: |
          apictl login dev \
            -u "${{ secrets.WSO2_USERNAME }}" \
            -p "${{ secrets.WSO2_PASSWORD }}" \
            -k

      - name: Show API project
        run: |
          pwd
          ls -la
          ls -la NewFlightsAPI

      - name: Import API
        run: |
          apictl import api \
            -f NewFlightsAPI \
            -e dev \
            -k
